### ISSUE TITLE
Problems handling binaries.

### ISSUE THREAD

**Issue by cesarvr** [bucharest-gold/roi#16]
Hi, just try to stream some binary from a server

``` javascript
// express.js service return send(new Buffer(data, 'binary'))
roi.post({endpoint: URL+'/binary'}, amp010)   
               .then(resp=>{
               let bin = Buffer.from(resp.body, 'binary'); 
               require('fs').writeFileSync('./img.bin', bin);
            })
             .catch(e=>console.log('error: ', e));
```

The file get corrupted:            
- expected 276 kb
- downloaded 274 kb  

I did try another library called [node-fetch](https://github.com/bitinn/node-fetch) , and it works, I took a look at the code difference is that they use stream API to handle the request and then transform to the wanted medium.

Cheers.

**Comment by helio-frota** [comment]
@cesarvr hi, `amp010` is a file ?

If yes then you can try `roi.upload(options, file)`

The roi upload function uses stream API.

Here is the 'fake server' part :
https://github.com/bucharest-gold/roi/blob/master/test/roi-test.js#L320-L330

Here is the upload test [ example ] :
https://github.com/bucharest-gold/roi/blob/master/test/roi-test.js#L332-L343

Also I noticed we have no upload example on readme.

Please let me know if it works.

**Comment by helio-frota** [comment]
Example added: 
https://github.com/bucharest-gold/roi#upload

**Comment by helio-frota** [comment]
The result of uploaded.jar running :

![a](https://cloud.githubusercontent.com/assets/6443576/19388920/38bca732-91f8-11e6-9c83-10cb7967be14.png)

**Comment by cesarvr** [comment]
The amp010 variable is just a JS object, the service read this object and generates a buffer(binary), then this buffer is sent to the client.

My problem happens when i'm try download the binary using the *roi.post* method, the file get corrupted. I think it should work if i can use the *roi.download* method but there is no way to pass HTTP method nor the object, so maybe could be a good feature to add or just use node stream API (like roi.download does) to handle all HTTP verbs. 

to reproduce: 

``` javascript
// in my case .post
app.get('/streamSomething', 

(res,resp)=>resp.status(200)
   .send(new Buffer( bunchOfData, 'binary') ) 
)

```

**Comment by helio-frota** [comment]
@cesarvr Now I got the issue.

1. Your app sends a binary
2. Your client is sending a POST with some data and needs a binary as result [a kind of download [_needs stream API_] ]

Thanks, I'm going to create a issue for it and link with your comment.

**Comment by helio-frota** [comment]
@cesarvr sorry the delay.

You can now try roi.postStream(options, yourDataHere, yourFileDestinationHere);

`roi.post(options, {foo: 1}, '/tmp/myfile.bin)`

Any problems please let me know.

**Comment by helio-frota** [comment]
Closing this for now.
