### ISSUE TITLE
Test CORS

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/roi#23]
We need check if this module is able to work with CORS.
If not, is good to add that capability.

**Comment by lance** [comment]
For reference https://github.com/hawkular/hawkular-apm-opentracing-javascript/pull/11/files#r87585296

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/roi/commit/0c11bc8554260124397b1f2a2bb91f651e8c0c38

looks like it working fine.
